// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxSaHWb5ciaBdvfq15WPjPjHfqzOfOdfs',
    appId: '1:51572570425:web:ada684f2c408f7703fd0e8',
    messagingSenderId: '51572570425',
    projectId: 'uas-ambw-9288b',
    authDomain: 'uas-ambw-9288b.firebaseapp.com',
    storageBucket: 'uas-ambw-9288b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7gg2HNvfeHKKlAEq8M77V1UW3vtfzjU8',
    appId: '1:51572570425:android:3d641edddc68dac13fd0e8',
    messagingSenderId: '51572570425',
    projectId: 'uas-ambw-9288b',
    storageBucket: 'uas-ambw-9288b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF043FOxuLD9rcKB1n8dKAC7ZEM4ct_C8',
    appId: '1:51572570425:ios:1f0ff4c0f8ad19153fd0e8',
    messagingSenderId: '51572570425',
    projectId: 'uas-ambw-9288b',
    storageBucket: 'uas-ambw-9288b.appspot.com',
    iosClientId: '51572570425-e3roegp2mb2h1lon1oqggbpfn4cnh5qf.apps.googleusercontent.com',
    iosBundleId: 'com.example.c1419004001',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCF043FOxuLD9rcKB1n8dKAC7ZEM4ct_C8',
    appId: '1:51572570425:ios:1f0ff4c0f8ad19153fd0e8',
    messagingSenderId: '51572570425',
    projectId: 'uas-ambw-9288b',
    storageBucket: 'uas-ambw-9288b.appspot.com',
    iosClientId: '51572570425-e3roegp2mb2h1lon1oqggbpfn4cnh5qf.apps.googleusercontent.com',
    iosBundleId: 'com.example.c1419004001',
  );
}
